config/routes.rb
PrismicioWebhookTester::Application.routes.draw do
  match 'webhook', to: 'welcome#webhook', via: :post

  root 'welcome#index'

  resources :calls

end

app/models/call.rb
class Call < ActiveRecord::Base

	def obfuscated_secret
		secret[0..2] + secret[3..-1].gsub(/./, '*')
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: [:show, :edit, :update, :destroy]

  # GET /calls
  # GET /calls.json
  def index
    @calls = Call.all
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(call_params)

    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render action: 'show', status: :created, location: @call }
      else
        format.html { render action: 'new' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:date, :type_webhook, :domain, :apiURL, :secret)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	protect_from_forgery with: :null_session

	def webhook
		req = ActiveSupport::JSON.decode(request.body)

		if Call.create({date: Time.now, type_webhook: req['type'], domain: req['domain'], apiURL: req['apiUrl'], secret: req['secret']})
			render text: "Webhook was properly written in DB"
		else
			render text: "There was an issue writing the webhook"
		end
	end

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :type_webhook %><br>
    <%= f.text_field :type_webhook %>
  </div>
  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :apiURL %><br>
    <%= f.text_field :apiURL %>
  </div>
  <div class="field">
    <%= f.label :secret %><br>
    <%= f.text_field :secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<h1>Listing calls</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Type</th>
      <th>Domain</th>
      <th>Apiurl</th>
      <th>Secret</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @calls.each do |call| %>
      <tr>
        <td><%= call.date %></td>
        <td><%= call.type_webhook %></td>
        <td><%= call.domain %></td>
        <td><%= call.apiURL %></td>
        <td><%= call.obfuscated_secret %></td>
        <td><%= link_to 'Show', call %></td>
        <td><%= link_to 'Edit', edit_call_path(call) %></td>
        <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @call.date %>
</p>

<p>
  <strong>Type:</strong>
  <%= @call.type_webhook %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @call.domain %>
</p>

<p>
  <strong>Apiurl:</strong>
  <%= @call.apiURL %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @call.obfuscated_secret %>
</p>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrismicioWebhookTester</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<p>Try calling something like:</p>

<code>curl -H "Content-Type: application/json" -d '{"type" : "api-update", "domain" : "example", "apiUrl" : "https://example.prismic.io/api", "secret" : "mySecretPassphrase"}' http://&lt;servername&gt;/webhook</code>